# Generated by Django 3.0.5 on 2022-09-23 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_user_tbl'),
    ]

    operations = [
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('discriptiom', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='news_img')),
            ],
        ),
    ]
